version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379/0
      - PYTHONPATH=/app
    command: >
      sh -c "pip install slowapi &&
             cd /app &&
             python -m uvicorn backend.main:app --host 0.0.0.0 --port 8000 --log-level debug"
    volumes:
      - /usr/share/tesseract-ocr:/usr/share/tesseract-ocr:ro
    depends_on:
      redis:
        condition: service_healthy
      ollama:
        condition: service_started

  frontend:
    container_name: my_ai_assistant_frontend
    build:
      context: ./foodsave-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - INTERNAL_API_BASE_URL=http://backend:8000
    depends_on:
      - backend

  redis:
    container_name: my_ai_assistant_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama
    container_name: my_ai_assistant_ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true

volumes:
  ollama_data:
